language: node_js
node_js:
  - "8"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
script:
  - npm run lint
  - npm run check-format
  - npm run cover
after_success:
  - npm run coverage-upload
